reporte:
    resource: "@ReporteBundle/Controller/"
    type:     annotation
    prefix:   /

proyecto:
    resource: "@ProyectoBundle/Controller/"
    type:     annotation
    prefix:   /

nomenclador:
    resource: "@NomencladorBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /