<?php

namespace Proxies\__CG__\ProyectoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProyectoConsejoTecnico extends \ProyectoBundle\Entity\ProyectoConsejoTecnico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'id', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'fecha', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'local', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'observacion', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'estado', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'consejoTecnico', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'proyecto', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'persona');
        }

        return array('__isInitialized__', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'id', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'fecha', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'local', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'observacion', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'estado', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'consejoTecnico', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'proyecto', '' . "\0" . 'ProyectoBundle\\Entity\\ProyectoConsejoTecnico' . "\0" . 'persona');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProyectoConsejoTecnico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', array($fecha));

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', array());

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocal($local)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocal', array($local));

        return parent::setLocal($local);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocal', array());

        return parent::getLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservacion($observacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservacion', array($observacion));

        return parent::setObservacion($observacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservacion', array());

        return parent::getObservacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsejoTecnico(\NomencladorBundle\Entity\ConsejoTecnico $consejoTecnico = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsejoTecnico', array($consejoTecnico));

        return parent::setConsejoTecnico($consejoTecnico);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsejoTecnico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsejoTecnico', array());

        return parent::getConsejoTecnico();
    }

    /**
     * {@inheritDoc}
     */
    public function setProyecto(\ProyectoBundle\Entity\Proyecto $proyecto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProyecto', array($proyecto));

        return parent::setProyecto($proyecto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProyecto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProyecto', array());

        return parent::getProyecto();
    }

    /**
     * {@inheritDoc}
     */
    public function addPersona(\NomencladorBundle\Entity\Persona $persona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPersona', array($persona));

        return parent::addPersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function removePersona(\NomencladorBundle\Entity\Persona $persona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePersona', array($persona));

        return parent::removePersona($persona);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersona', array());

        return parent::getPersona();
    }

}
