services:
    scs.util:
        class: NomencladorBundle\Services\Util
        arguments: ['@doctrine.orm.entity_manager', '@validator']

#    nomenclador.example:
#        class: NomencladorBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
